<?php 

use App\Http\Controllers\UserController;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\client\ClientController;
use App\Http\Controllers\admin\AdminController; 



//client
Route::get('/', [ClientController::class, 'home']);
Route::get('/cart', [ClientController::class, 'cart']);
Route::get('/shop', [ClientController::class, 'shop']);
Route::get('/blog', [ClientController::class, 'blog']);

//admin
Route::get('/404', [AdminController::class, 'show404']); 
Route::get('/500', [AdminController::class, 'show500']);
Route::get('/activity_stream', [AdminController::class, 'activity_stream']);
Route::get('/agile_board', [AdminController::class, 'agile_board']);
Route::get('/article', [AdminController::class, 'article']);
Route::get('/badges_labels', [AdminController::class, 'badges_labels']);
Route::get('/basic_gallery', [AdminController::class, 'basic_gallery']);
Route::get('/blogs', [AdminController::class, 'blogs']);
Route::get('/buttons', [AdminController::class, 'buttons']);
Route::get('/c3', [AdminController::class, 'c3']);
Route::get('/calendar', [AdminController::class, 'calendar']);
Route::get('/carousel', [AdminController::class, 'carousel']);
Route::get('/chat_view', [AdminController::class, 'chat_view']);
Route::get('/clients', [AdminController::class, 'clients']);
Route::get('/clipboard', [AdminController::class, 'clipboard']);
Route::get('/code_editor', [AdminController::class, 'code_editor']);
Route::get('/contacts_2', [AdminController::class, 'contacts_2']);
Route::get('/contacts', [AdminController::class, 'contacts']);
Route::get('/css_animation', [AdminController::class, 'css_animation']);
Route::get('/dashboard_2', [AdminController::class, 'dashboard_2']);
Route::get('/dashboard_3', [AdminController::class, 'dashboard_3']);
Route::get('/dashboard_4_1', [AdminController::class, 'dashboard_4_1']);
Route::get('/dashboard_4', [AdminController::class, 'dashboard_4']);
Route::get('/dashboard_5', [AdminController::class, 'dashboard_5']);
Route::get('/datamaps', [AdminController::class, 'datamaps']);
Route::get('/diff', [AdminController::class, 'diff']);
Route::get('/draggable_panels', [AdminController::class, 'draggable_panels']);
Route::get('/ecommerce_payments', [AdminController::class, 'ecommerce_payments']);
Route::get('/ecommerce_product_detail', [AdminController::class, 'ecommerce_product_detail']);
Route::get('/ecommerce_product_list', [AdminController::class, 'ecommerce_product_list']);
Route::get('/ecommerce_product', [AdminController::class, 'ecommerce_product']);
Route::get('/ecommerce_products_grid', [AdminController::class, 'ecommerce_products_grid']);
Route::get('/ecommerce_cart', [AdminController::class, 'ecommerce_cart']);
Route::get('/ecommerce_orders', [AdminController::class, 'ecommerce_orders']);
Route::get('/email_template', [AdminController::class, 'email_template']);
Route::get('/empty_page', [AdminController::class, 'empty_page']);
Route::get('/faq', [AdminController::class, 'faq']);
Route::get('/file_manager', [AdminController::class, 'file_manager']);
Route::get('/forgot_password', [AdminController::class, 'forgot_password']);
Route::get('/form_advanced', [AdminController::class, 'form_advanced']);
Route::get('/form_autocomplete', [AdminController::class, 'form_autocomplete']);
Route::get('/form_basic', [AdminController::class, 'form_basic']);
Route::get('/form_editors', [AdminController::class, 'form_editors']);
Route::get('/form_file_upload', [AdminController::class, 'form_file_upload']);
Route::get('/form_markdown', [AdminController::class, 'form_markdown']);
Route::get('/form_wizard', [AdminController::class, 'form_wizard']);
Route::get('/forum_main', [AdminController::class, 'forum_main']);
Route::get('/forum_post', [AdminController::class, 'forum_post']);
Route::get('/fullheight', [AdminController::class, 'fullheight']);
Route::get('/google_maps', [AdminController::class, 'google_maps']);
Route::get('/graph_chartist', [AdminController::class, 'graph_chartist']);
Route::get('/graph_chartjs', [AdminController::class, 'graph_chartjs']);
Route::get('/graph_flot', [AdminController::class, 'graph_flot']);
Route::get('/graph_morris', [AdminController::class, 'graph_morris']);
Route::get('/graph_peity', [AdminController::class, 'graph_peity']);
Route::get('/graph_rickshaw', [AdminController::class, 'graph_rickshaw']);
Route::get('/graph_sparkline', [AdminController::class, 'graph_sparkline']);
Route::get('/frid_options', [AdminController::class, 'frid_options']);
Route::get('/helper_classes', [AdminController::class, 'helper_classes']);
Route::get('/i18support', [AdminController::class, 'i18support']);
Route::get('/icons', [AdminController::class, 'icons']);
Route::get('/idle_timer', [AdminController::class, 'idle_timer']);
Route::get('/index', [AdminController::class, 'index']);
Route::get('/invoice_print', [AdminController::class, 'invoice_print']);
Route::get('/invoice', [AdminController::class, 'invoice']);
Route::get('/issue_tracker', [AdminController::class, 'issue_tracker']);
Route::get('/jq_grid', [AdminController::class, 'jq_grid']);
Route::get('/landing', [AdminController::class, 'landing']);
Route::get('/layouts', [AdminController::class, 'layouts']);
Route::get('/loading_buttons', [AdminController::class, 'loading_buttons']);
Route::get('/lockscreen', [AdminController::class, 'lockscreen']);
Route::get('/login_two_clolumns', [AdminController::class, 'login_two_clolumns']);
Route::get('/login', [AdminController::class, 'login']);
Route::get('/mail_compose', [AdminController::class, 'mail_compose']);
Route::get('/mail_detail', [AdminController::class, 'mail_detail']);
Route::get('/mailbox', [AdminController::class, 'mailbox']);
Route::get('/masonry', [AdminController::class, 'masonry']);
Route::get('/md_skin', [AdminController::class, 'md_skin']);
Route::get('/metrics', [AdminController::class, 'metrics']);
Route::get('/modal_window', [AdminController::class, 'modal_window']);
Route::get('/nestable_list', [AdminController::class, 'nestable_list']);
Route::get('/notifications', [AdminController::class, 'notifications']);
Route::get('/off_canvas_menu', [AdminController::class, 'off_canvas_menu']);
Route::get('/package', [AdminController::class, 'package']);
Route::get('/password_meter', [AdminController::class, 'password_meter']);
Route::get('/pdf_viewer', [AdminController::class, 'pdf_viewer']);
Route::get('/pin_board', [AdminController::class, 'pin_board']);
Route::get('/profile_2', [AdminController::class, 'profile_2']);
Route::get('/profile', [AdminController::class, 'profile']);
Route::get('/project_detail', [AdminController::class, 'project_detail']);
Route::get('/projects', [AdminController::class, 'projects']);
Route::get('/register', [AdminController::class, 'register']);
Route::get('/resizeable_panels', [AdminController::class, 'resizeable_panels']);
Route::get('/search_results', [AdminController::class, 'search_results']);
Route::get('/skin_config', [AdminController::class, 'skin_config']);
Route::get('/slick_carousel', [AdminController::class, 'slick_carousel']);
Route::get('/social_buttons', [AdminController::class, 'social_buttons']);
Route::get('/social_feed', [AdminController::class, 'social_feed']);
Route::get('/spinners_usage', [AdminController::class, 'spinners_usage']);
Route::get('/spinners', [AdminController::class, 'spinners']);
Route::get('/sweetalert', [AdminController::class, 'sweetalert']);
Route::get('/table_basic', [AdminController::class, 'table_basic']);
Route::get('/table_data_tables', [AdminController::class, 'table_data_tables']);
Route::get('/table_foo_table', [AdminController::class, 'table_foo_table']);
Route::get('/tabs_panels', [AdminController::class, 'tabs_panels']);
Route::get('/tabs', [AdminController::class, 'tabs']);
Route::get('/teams_board', [AdminController::class, 'teams_board']);
Route::get('/text_spinners', [AdminController::class, 'text_spinners']);
Route::get('/timeline_2', [AdminController::class, 'timeline_2']);
Route::get('/timeline', [AdminController::class, 'timeline']);
Route::get('/tinycon', [AdminController::class, 'tinycon']);
Route::get('/toastr_notifications', [AdminController::class, 'toastr_notifications']);
Route::get('/tour', [AdminController::class, 'tour']);
Route::get('/tree_view', [AdminController::class, 'tree_view']);
Route::get('/truncate', [AdminController::class, 'truncate']);
Route::get('/typography', [AdminController::class, 'typography']);
Route::get('/validation', [AdminController::class, 'validation']);
Route::get('/video', [AdminController::class, 'video']);
Route::get('/vote_list', [AdminController::class, 'vote_list']);
Route::get('/widgets', [AdminController::class, 'widgets']);
// Route::get('/activity_stream', [AdminController::class, 'activity_stream']);
// Route::get('/activity_stream', [AdminController::class, 'activity_stream']);
// Route::get('/activity_stream', [AdminController::class, 'activity_stream']);
// Route::get('/activity_stream', [AdminController::class, 'activity_stream']);
