name: CI/CD Laravel Deployment

on:
  push:
    branches:
      - main  # Chạy khi có thay đổi trên nhánh main

jobs:
  deploy:
    name: Deploy Laravel Application to aaPanel Server
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.4
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Check SSH access  # Kiểm tra kết nối SSH trước
      run: ssh -o StrictHostKeyChecking=no root@157.10.45.131 "echo 'SSH connection successful'"

    - name: Deploy to Server
      run: |
        ssh -o StrictHostKeyChecking=no root@157.10.45.131 << 'EOF'
          cd /www/wwwroot/beebook.site

          # Pull code từ GitHub repository
          git pull origin main
          
          # Cài đặt các phụ thuộc Laravel
          composer install --no-dev --optimize-autoloader
          
          # Chạy lệnh Laravel migrate để cập nhật database
          php artisan migrate --force

          # Clear cache, config, views
          php artisan cache:clear
          php artisan config:clear
          php artisan config:cache
          php artisan view:clear

          # Đặt quyền cho thư mục
          chown -R www:www storage
          chown -R www:www bootstrap/cache

          # Đặt quyền cho thư mục storage và bootstrap/cache
          sudo chown -R www:www storage
          sudo chown -R www:www bootstrap/cache

          # Đảm bảo quyền ghi cho các thư mục
          sudo chmod -R 775 storage
          sudo chmod -R 775 bootstrap/cache


          # Khởi động lại dịch vụ web (Nginx hoặc Apache)
          # systemctl restart nginx
        EOF
