name: CI/CD Laravel Deployment

on:
  push:
    branches:
      - main  # Chạy khi có thay đổi trên nhánh main

jobs:
  deploy:
    name: Deploy Laravel Application to aaPanel Server
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.4
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Deploy to Server
      run: |
        ssh -o StrictHostKeyChecking=no user@your_server_ip << 'EOF'
          # Chuyển tới thư mục chứa dự án Laravel trên máy chủ
          cd /path/to/your/laravel/project
          
          # Pull code từ GitHub repository
          git pull origin main
          
          # Cài đặt các phụ thuộc Laravel
          composer install --no-dev --optimize-autoloader
          
          # Chạy lệnh Laravel migrate để cập nhật database
          php artisan migrate --force

          # Chạy lệnh để clear cache, config, và views
          php artisan cache:clear
          php artisan config:clear
          php artisan config:cache
          php artisan view:clear

          # Đặt quyền cho thư mục storage và bootstrap/cache
          chown -R www-data:www-data storage
          chown -R www-data:www-data bootstrap/cache

          # Khởi động lại dịch vụ web (Nginx hoặc Apache)
          systemctl restart nginx
        EOF
